// <auto-generated />
using System;
using ClinicSoft.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicSoft.Migrations
{
    [DbContext(typeof(ClinicSoftContext))]
    [Migration("20260408174713_RestoreDatabaseSchema")]
    partial class RestoreDatabaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicSoft.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<int>("GenderCode")
                        .HasColumnType("integer")
                        .HasColumnName("gender_code");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("admins_pkey");

                    b.HasIndex("GenderCode");

                    b.HasIndex(new[] { "Email" }, "admins_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "admins_phone_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "admins_user_id_key")
                        .IsUnique();

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scheduled_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'scheduled'::character varying");

                    b.HasKey("Id")
                        .HasName("appointments_pkey");

                    b.HasIndex(new[] { "DoctorId", "ScheduledTime" }, "appointments_doctor_time_key")
                        .IsUnique();

                    b.HasIndex(new[] { "PatientId", "DoctorId" }, "idx_appointments_patient_doctor");

                    b.HasIndex(new[] { "ScheduledTime" }, "idx_appointments_scheduled_time");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("departments_pkey");

                    b.HasIndex(new[] { "Name" }, "departments_name_key")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("diagnoses_pkey");

                    b.HasIndex(new[] { "Name" }, "diagnoses_name_key")
                        .IsUnique();

                    b.ToTable("diagnoses", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<int>("GenderCode")
                        .HasColumnType("integer")
                        .HasColumnName("gender_code");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("middle_name");

                    b.Property<int>("OfficeId")
                        .HasColumnType("integer")
                        .HasColumnName("office_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("integer")
                        .HasColumnName("speciality_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("doctors_pkey");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("GenderCode");

                    b.HasIndex("OfficeId");

                    b.HasIndex("SpecialityId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "Phone" }, "doctors_phone_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "idx_doctors_email")
                        .IsUnique()
                        .HasFilter("((email IS NOT NULL) AND ((email)::text <> ''::text))");

                    b.HasIndex(new[] { "UserId" }, "idx_doctors_user_id");

                    b.ToTable("doctors", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.DoctorStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("doctor_statuses_pkey");

                    b.HasIndex(new[] { "Name" }, "doctor_statuses_name_key")
                        .IsUnique();

                    b.ToTable("doctor_statuses", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<int?>("DocumentTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("document_template_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("documents_pkey");

                    b.HasIndex("DocumentTemplateId");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_documents_created_at");

                    b.HasIndex(new[] { "DoctorId" }, "idx_documents_doctor_id");

                    b.HasIndex(new[] { "PatientId" }, "idx_documents_patient_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.DocumentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("document_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("document_templates_pkey");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex(new[] { "Name" }, "document_templates_name_key")
                        .IsUnique();

                    b.ToTable("document_templates", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("document_types_pkey");

                    b.HasIndex(new[] { "Name" }, "document_types_name_key")
                        .IsUnique();

                    b.ToTable("document_types", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.DosageForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("dosage_forms_pkey");

                    b.HasIndex(new[] { "Name" }, "dosage_forms_name_key")
                        .IsUnique();

                    b.ToTable("dosage_forms", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("genders_pkey");

                    b.HasIndex(new[] { "Name" }, "genders_name_key")
                        .IsUnique();

                    b.ToTable("genders", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.LabOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OrderedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ordered_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<int>("VisitId")
                        .HasColumnType("integer")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("lab_orders_pkey");

                    b.HasIndex(new[] { "DoctorId" }, "idx_lab_orders_doctor_id");

                    b.HasIndex(new[] { "PatientId" }, "idx_lab_orders_patient_id");

                    b.HasIndex(new[] { "VisitId" }, "idx_lab_orders_visit_id");

                    b.ToTable("lab_orders", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.LabOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LabOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("lab_order_id");

                    b.Property<int>("TestTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("test_type_id");

                    b.HasKey("Id")
                        .HasName("lab_order_items_pkey");

                    b.HasIndex("TestTypeId");

                    b.HasIndex(new[] { "LabOrderId" }, "idx_lab_order_items_lab_order_id");

                    b.HasIndex(new[] { "LabOrderId", "TestTypeId" }, "lab_order_items_order_test_key")
                        .IsUnique();

                    b.ToTable("lab_order_items", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.LabResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("LabOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("lab_order_id");

                    b.Property<int>("PerformedBy")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by");

                    b.HasKey("Id")
                        .HasName("lab_results_pkey");

                    b.HasIndex(new[] { "PerformedBy" }, "idx_lab_results_performed_by");

                    b.HasIndex(new[] { "LabOrderId" }, "lab_results_lab_order_id_key")
                        .IsUnique();

                    b.ToTable("lab_results", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.LabResultItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LabResultId")
                        .HasColumnType("integer")
                        .HasColumnName("lab_result_id");

                    b.Property<string>("ResultValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_value");

                    b.Property<int>("TestTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("test_type_id");

                    b.HasKey("Id")
                        .HasName("lab_result_items_pkey");

                    b.HasIndex("TestTypeId");

                    b.HasIndex(new[] { "LabResultId" }, "idx_lab_result_items_lab_result_id");

                    b.HasIndex(new[] { "LabResultId", "TestTypeId" }, "lab_result_items_result_test_key")
                        .IsUnique();

                    b.ToTable("lab_result_items", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.LabTestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NormalRange")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normal_range");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("lab_test_types_pkey");

                    b.HasIndex("UnitId");

                    b.HasIndex(new[] { "Name" }, "idx_lab_test_types_name");

                    b.HasIndex(new[] { "Name" }, "lab_test_types_name_key")
                        .IsUnique();

                    b.ToTable("lab_test_types", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.MedicalCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allergies");

                    b.Property<string>("ChronicConditions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chronic_conditions");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("InsuranceNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("insurance_number");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.HasKey("Id")
                        .HasName("medical_cards_pkey");

                    b.HasIndex(new[] { "InsuranceNumber" }, "idx_medical_cards_insurance_number");

                    b.HasIndex(new[] { "InsuranceNumber" }, "medical_cards_insurance_number_key")
                        .IsUnique();

                    b.HasIndex(new[] { "PatientId" }, "medical_cards_patient_id_key")
                        .IsUnique();

                    b.ToTable("medical_cards", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.MedicalSpeciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("medical_specialities_pkey");

                    b.HasIndex(new[] { "Name" }, "medical_specialities_name_key")
                        .IsUnique();

                    b.ToTable("medical_specialities", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DosageFormId")
                        .HasColumnType("integer")
                        .HasColumnName("dosage_form_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("medications_pkey");

                    b.HasIndex("DosageFormId");

                    b.HasIndex(new[] { "Name" }, "idx_medications_name");

                    b.HasIndex(new[] { "Name", "DosageFormId" }, "medications_name_dosage_form_key")
                        .IsUnique();

                    b.ToTable("medications", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("offices_pkey");

                    b.HasIndex(new[] { "Number" }, "offices_number_key")
                        .IsUnique();

                    b.ToTable("offices", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<int>("GenderCode")
                        .HasColumnType("integer")
                        .HasColumnName("gender_code");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("patients_pkey");

                    b.HasIndex("GenderCode");

                    b.HasIndex(new[] { "UserId" }, "idx_patients_user_id");

                    b.HasIndex(new[] { "Email" }, "patients_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "patients_phone_key")
                        .IsUnique();

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.PrescribedMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dosage");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<int>("MedicationId")
                        .HasColumnType("integer")
                        .HasColumnName("medication_id");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("prescription_id");

                    b.HasKey("Id")
                        .HasName("prescribed_medications_pkey");

                    b.HasIndex("MedicationId");

                    b.HasIndex(new[] { "PrescriptionId" }, "idx_prescribed_medications_prescription_id");

                    b.ToTable("prescribed_medications", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::character varying");

                    b.Property<int>("VisitId")
                        .HasColumnType("integer")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("prescriptions_pkey");

                    b.HasIndex(new[] { "DoctorId" }, "idx_prescriptions_doctor_id");

                    b.HasIndex(new[] { "VisitId" }, "idx_prescriptions_visit_id");

                    b.ToTable("prescriptions", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.Registrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<int>("GenderCode")
                        .HasColumnType("integer")
                        .HasColumnName("gender_code");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("registrators_pkey");

                    b.HasIndex("GenderCode");

                    b.HasIndex(new[] { "Email" }, "registrators_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "registrators_phone_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "registrators_user_id_key")
                        .IsUnique();

                    b.ToTable("registrators", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Name" }, "roles_name_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.UnitsOfMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("units_of_measurement_pkey");

                    b.HasIndex(new[] { "Symbol" }, "units_of_measurement_symbol_key")
                        .IsUnique();

                    b.ToTable("units_of_measurement", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "RoleId" }, "idx_users_role_id");

                    b.HasIndex(new[] { "Login" }, "users_login_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    b.Property<string>("ChiefComplaint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chief_complaint");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("integer")
                        .HasColumnName("diagnosis_id");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("VisitTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("visit_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("visits_pkey");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex(new[] { "AppointmentId" }, "idx_visits_appointment_id");

                    b.HasIndex(new[] { "DoctorId" }, "idx_visits_doctor_id");

                    b.HasIndex(new[] { "PatientId" }, "idx_visits_patient_id");

                    b.ToTable("visits", (string)null);
                });

            modelBuilder.Entity("ClinicSoft.Models.Admin", b =>
                {
                    b.HasOne("ClinicSoft.Models.Gender", "GenderCodeNavigation")
                        .WithMany("Admins")
                        .HasForeignKey("GenderCode")
                        .IsRequired()
                        .HasConstraintName("fk_admin_gender");

                    b.HasOne("ClinicSoft.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("ClinicSoft.Models.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("admins_user_id_fkey");

                    b.Navigation("GenderCodeNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicSoft.Models.Appointment", b =>
                {
                    b.HasOne("ClinicSoft.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("appointments_doctor_id_fkey");

                    b.HasOne("ClinicSoft.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("appointments_patient_id_fkey");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicSoft.Models.Doctor", b =>
                {
                    b.HasOne("ClinicSoft.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("doctors_department_id_fkey");

                    b.HasOne("ClinicSoft.Models.Gender", "GenderCodeNavigation")
                        .WithMany("Doctors")
                        .HasForeignKey("GenderCode")
                        .IsRequired()
                        .HasConstraintName("doctors_gender_code_fkey");

                    b.HasOne("ClinicSoft.Models.Office", "Office")
                        .WithMany("Doctors")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("doctors_office_id_fkey");

                    b.HasOne("ClinicSoft.Models.MedicalSpeciality", "Speciality")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialityId")
                        .IsRequired()
                        .HasConstraintName("doctors_speciality_id_fkey");

                    b.HasOne("ClinicSoft.Models.DoctorStatus", "Status")
                        .WithMany("Doctors")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("doctors_status_id_fkey");

                    b.HasOne("ClinicSoft.Models.User", "User")
                        .WithMany("Doctors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("doctors_user_id_fkey");

                    b.Navigation("Department");

                    b.Navigation("GenderCodeNavigation");

                    b.Navigation("Office");

                    b.Navigation("Speciality");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicSoft.Models.Document", b =>
                {
                    b.HasOne("ClinicSoft.Models.Doctor", "Doctor")
                        .WithMany("Documents")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("documents_doctor_id_fkey");

                    b.HasOne("ClinicSoft.Models.DocumentTemplate", "DocumentTemplate")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("documents_document_template_id_fkey");

                    b.HasOne("ClinicSoft.Models.Patient", "Patient")
                        .WithMany("Documents")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("documents_patient_id_fkey");

                    b.Navigation("Doctor");

                    b.Navigation("DocumentTemplate");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicSoft.Models.DocumentTemplate", b =>
                {
                    b.HasOne("ClinicSoft.Models.DocumentType", "DocumentType")
                        .WithMany("DocumentTemplates")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("document_templates_document_type_id_fkey");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("ClinicSoft.Models.LabOrder", b =>
                {
                    b.HasOne("ClinicSoft.Models.Doctor", "Doctor")
                        .WithMany("LabOrders")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("lab_orders_doctor_id_fkey");

                    b.HasOne("ClinicSoft.Models.Patient", "Patient")
                        .WithMany("LabOrders")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("lab_orders_patient_id_fkey");

                    b.HasOne("ClinicSoft.Models.Visit", "Visit")
                        .WithMany("LabOrders")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("lab_orders_visit_id_fkey");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("ClinicSoft.Models.LabOrderItem", b =>
                {
                    b.HasOne("ClinicSoft.Models.LabOrder", "LabOrder")
                        .WithMany("LabOrderItems")
                        .HasForeignKey("LabOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("lab_order_items_lab_order_id_fkey");

                    b.HasOne("ClinicSoft.Models.LabTestType", "TestType")
                        .WithMany("LabOrderItems")
                        .HasForeignKey("TestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("lab_order_items_test_type_id_fkey");

                    b.Navigation("LabOrder");

                    b.Navigation("TestType");
                });

            modelBuilder.Entity("ClinicSoft.Models.LabResult", b =>
                {
                    b.HasOne("ClinicSoft.Models.LabOrder", "LabOrder")
                        .WithOne("LabResult")
                        .HasForeignKey("ClinicSoft.Models.LabResult", "LabOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("lab_results_lab_order_id_fkey");

                    b.HasOne("ClinicSoft.Models.Doctor", "PerformedByNavigation")
                        .WithMany("LabResults")
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("lab_results_performed_by_fkey");

                    b.Navigation("LabOrder");

                    b.Navigation("PerformedByNavigation");
                });

            modelBuilder.Entity("ClinicSoft.Models.LabResultItem", b =>
                {
                    b.HasOne("ClinicSoft.Models.LabResult", "LabResult")
                        .WithMany("LabResultItems")
                        .HasForeignKey("LabResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("lab_result_items_lab_result_id_fkey");

                    b.HasOne("ClinicSoft.Models.LabTestType", "TestType")
                        .WithMany("LabResultItems")
                        .HasForeignKey("TestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("lab_result_items_test_type_id_fkey");

                    b.Navigation("LabResult");

                    b.Navigation("TestType");
                });

            modelBuilder.Entity("ClinicSoft.Models.LabTestType", b =>
                {
                    b.HasOne("ClinicSoft.Models.UnitsOfMeasurement", "Unit")
                        .WithMany("LabTestTypes")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("lab_test_types_unit_id_fkey");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ClinicSoft.Models.MedicalCard", b =>
                {
                    b.HasOne("ClinicSoft.Models.Patient", "Patient")
                        .WithOne("MedicalCard")
                        .HasForeignKey("ClinicSoft.Models.MedicalCard", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("medical_cards_patient_id_fkey");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicSoft.Models.Medication", b =>
                {
                    b.HasOne("ClinicSoft.Models.DosageForm", "DosageForm")
                        .WithMany("Medications")
                        .HasForeignKey("DosageFormId")
                        .IsRequired()
                        .HasConstraintName("medications_dosage_form_id_fkey");

                    b.Navigation("DosageForm");
                });

            modelBuilder.Entity("ClinicSoft.Models.Patient", b =>
                {
                    b.HasOne("ClinicSoft.Models.Gender", "GenderCodeNavigation")
                        .WithMany("Patients")
                        .HasForeignKey("GenderCode")
                        .IsRequired()
                        .HasConstraintName("patients_gender_code_fkey");

                    b.HasOne("ClinicSoft.Models.User", "User")
                        .WithMany("Patients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("patients_user_id_fkey");

                    b.Navigation("GenderCodeNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicSoft.Models.PrescribedMedication", b =>
                {
                    b.HasOne("ClinicSoft.Models.Medication", "Medication")
                        .WithMany("PrescribedMedications")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("prescribed_medications_medication_id_fkey");

                    b.HasOne("ClinicSoft.Models.Prescription", "Prescription")
                        .WithMany("PrescribedMedications")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("prescribed_medications_prescription_id_fkey");

                    b.Navigation("Medication");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("ClinicSoft.Models.Prescription", b =>
                {
                    b.HasOne("ClinicSoft.Models.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("prescriptions_doctor_id_fkey");

                    b.HasOne("ClinicSoft.Models.Visit", "Visit")
                        .WithMany("Prescriptions")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("prescriptions_visit_id_fkey");

                    b.Navigation("Doctor");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("ClinicSoft.Models.Registrator", b =>
                {
                    b.HasOne("ClinicSoft.Models.Gender", "GenderCodeNavigation")
                        .WithMany("Registrators")
                        .HasForeignKey("GenderCode")
                        .IsRequired()
                        .HasConstraintName("registrators_gender_code_fkey");

                    b.HasOne("ClinicSoft.Models.User", "User")
                        .WithOne("Registrator")
                        .HasForeignKey("ClinicSoft.Models.Registrator", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("registrators_user_id_fkey");

                    b.Navigation("GenderCodeNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicSoft.Models.User", b =>
                {
                    b.HasOne("ClinicSoft.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("users_role_id_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ClinicSoft.Models.Visit", b =>
                {
                    b.HasOne("ClinicSoft.Models.Appointment", "Appointment")
                        .WithMany("Visits")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("visits_appointment_id_fkey");

                    b.HasOne("ClinicSoft.Models.Diagnosis", "Diagnosis")
                        .WithMany("Visits")
                        .HasForeignKey("DiagnosisId")
                        .IsRequired()
                        .HasConstraintName("visits_diagnosis_id_fkey");

                    b.HasOne("ClinicSoft.Models.Doctor", "Doctor")
                        .WithMany("Visits")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("visits_doctor_id_fkey");

                    b.HasOne("ClinicSoft.Models.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("visits_patient_id_fkey");

                    b.Navigation("Appointment");

                    b.Navigation("Diagnosis");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicSoft.Models.Appointment", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("ClinicSoft.Models.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("ClinicSoft.Models.Diagnosis", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("ClinicSoft.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Documents");

                    b.Navigation("LabOrders");

                    b.Navigation("LabResults");

                    b.Navigation("Prescriptions");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("ClinicSoft.Models.DoctorStatus", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("ClinicSoft.Models.DocumentTemplate", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ClinicSoft.Models.DocumentType", b =>
                {
                    b.Navigation("DocumentTemplates");
                });

            modelBuilder.Entity("ClinicSoft.Models.DosageForm", b =>
                {
                    b.Navigation("Medications");
                });

            modelBuilder.Entity("ClinicSoft.Models.Gender", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Doctors");

                    b.Navigation("Patients");

                    b.Navigation("Registrators");
                });

            modelBuilder.Entity("ClinicSoft.Models.LabOrder", b =>
                {
                    b.Navigation("LabOrderItems");

                    b.Navigation("LabResult");
                });

            modelBuilder.Entity("ClinicSoft.Models.LabResult", b =>
                {
                    b.Navigation("LabResultItems");
                });

            modelBuilder.Entity("ClinicSoft.Models.LabTestType", b =>
                {
                    b.Navigation("LabOrderItems");

                    b.Navigation("LabResultItems");
                });

            modelBuilder.Entity("ClinicSoft.Models.MedicalSpeciality", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("ClinicSoft.Models.Medication", b =>
                {
                    b.Navigation("PrescribedMedications");
                });

            modelBuilder.Entity("ClinicSoft.Models.Office", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("ClinicSoft.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Documents");

                    b.Navigation("LabOrders");

                    b.Navigation("MedicalCard");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("ClinicSoft.Models.Prescription", b =>
                {
                    b.Navigation("PrescribedMedications");
                });

            modelBuilder.Entity("ClinicSoft.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ClinicSoft.Models.UnitsOfMeasurement", b =>
                {
                    b.Navigation("LabTestTypes");
                });

            modelBuilder.Entity("ClinicSoft.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Doctors");

                    b.Navigation("Patients");

                    b.Navigation("Registrator");
                });

            modelBuilder.Entity("ClinicSoft.Models.Visit", b =>
                {
                    b.Navigation("LabOrders");

                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
